sudo: false
matrix:
  include:
    - language: ruby
      install:
        - env | grep TRAVIS > .env
        - env | grep CI >> .env
        - env | grep MITXPRO_BASE_URL >> .env
      script: docker-compose -f docker-compose.yml -f docker-compose.travis.yml run web /src/travis/python_tests.sh
      services:
        - docker
      env:
        name: Python
    - language: node_js
      before_install:
        - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
        - export PATH="$HOME/.yarn/bin:$PATH"
      node_js:
        - "10.15.1"
      script: bash ./travis/js_tests.sh
      cache: yarn
      env:
        name: JavaScript
